### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by geekedtv** [zusam/zusam#35]
Please make docker easier to run. You curl installer is not working for me.

**Comment by nrobinaubertin** [comment]
Hi,  
Thanks for pointing that out.  
I made some fixes to the code and the documentation on the master branch following your input. I will release a new version with more fixes in the coming month. In the mean time, please use the following curl command `curl -Ls https://github.com/zusam/zusam/archive/refs/heads/master.tar.gz | tar xz --strip 1` to pull from master instead of the `0.5` tag (all these informations were added in the fixed documentation on the master branch).

**Comment by geekedtv** [comment]
env: can't execute 'php': No such file or directory

**Comment by geekedtv** [comment]
Got it running thanks.
