### ISSUE TITLE
Please, do not abandon this fantastic tool 

### ISSUE THREAD

**Issue by edersong** [zusam/zusam#56]

**Comment by nrobinaubertin** [comment]
Thank you for these kind words.

Working on Zusam is hard for me this year because I switched jobs (and the new one is taking a lot of my mental bandwidth). I also changed country this month so a lot is going on.
Another general issue is that I use php/javascript only for Zusam and don't really enjoy working with those languages anymore.

I **will** eventually work again on it. I'm using Zusam everyday with my family and friends.

**Comment by edersong** [comment]
Ok, no problem and good luck on your new challenge.
Me too, using Zusam as a personal note taking (a group only with me :-)) and other groups with family and friends.
Count me in in case you need help to test anything else.

**Comment by nrobinaubertin** [comment]
Don't hesitate to open issues for bugs and features
